site_name: Nightscout
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- Home: 'index.md'
- Nightscout:
    - 'Nightscout Overview': 'nightscout/overview.md'
    - 'Create your Nightscout site': 'nightscout/new_user.md'
    - 'Setup your Nighscout': 'nightscout/setup_variables.md'
    - 'Troubleshooting': 'nightscout/troublehoot.md'
    - 'Nightscout stopped working': 'nightscout/mlab_cleanup.md'
    - 'IFTTT': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
    - 'Reports': 'nightscout/reports.md'
- Update:
    - 'Updating your site': 'update/update.md'
    - 'Migrating to Atlas': 'update/migrate_heroku.md'
    - 'Migrating from Azure': 'update/migrate_azure.md'
